services:
  mysql:
    image: mysql:8.0
    container_name: spring-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdb
    ports:
      - "3306:3306"
